### ISSUE TITLE
Add support for syntax highlighting

### ISSUE THREAD

**Issue by KrauseFx** [KrauseFx/markdown-to-html-github-style#1]
Code blocks currently don't support syntax highlighting, however that's something that's rather easy to add. For a minimalistic stylesheet we could take the styles from [krausefx.com/css](https://github.com/KrauseFx/krausefx.com/blob/021186e228e183904af68ad8fc500c35107f00ae/assets/main.scss#L345-L438).

There are many libraries that support syntax highlighting to HTML, some even come with nice stylesheets. We gotta find one that's similar to GitHub

**Comment by FarazPatankar** [comment]
Thoughts on using [Prism](https://prismjs.com/) for the syntax highlighting?

**Comment by KrauseFx** [comment]
I have no preferences, as long as it's plain simple, well maintained and works well

**Comment by FarazPatankar** [comment]
I believe it ticks all the boxes. I am going to try and send a PR your way soon.

**Comment by KrauseFx** [comment]
Cool, thanks, and yah looks like it's MIT licensed 👍  https://github.com/PrismJS/prism/blob/master/LICENSE

**Comment by KrauseFx** [comment]
Working on this now
