### ISSUE TITLE
Table is rendering as markdown

### ISSUE THREAD

**Issue by ghost** [KrauseFx/markdown-to-html-github-style#11]
![Screenshot](https://user-images.githubusercontent.com/45569460/59677905-a9e04c00-91e8-11e9-9d7b-9e2b97c5c595.png)

**Comment by vitale232** [comment]
I came across this issue, too. Just add `tables: true` as an option in the `showdown.Converter` instantiation.

**Comment by KrauseFx** [comment]
Nice, thanks https://github.com/KrauseFx/markdown-to-html-github-style/commit/db9e23f83ac9af19638b6988e327aa340fbc862a
