### ISSUE TITLE
<meta charset="UTF-8"> by default?

### ISSUE THREAD

**Issue by juj** [KrauseFx/markdown-to-html-github-style#22]
It seems to be a de facto practice on modern web sites to use UTF-8, i.e.

```
<head>
  <meta charset="UTF-8">
</head>
```

This way one does not need to write the awkward `&auml;` etc. codes to represent letter `ä` for example. Maybe it would make sense to have that meta tag be generated in all output by default?

**Comment by KrauseFx** [comment]
Yes good call, pushing a fix now

**Comment by KrauseFx** [comment]
Done
